<a href="https://colab.research.google.com/github/Muniba11/Advance-SQL/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Amazon Sale Report.csv to Amazon Sale Report (1).csv

In [ ]:
import pandas as pd
df = pd.read_csv("Amazon Sale Report.csv")
pd.set_option('display.max_columns', None)
df.head(2)

/tmp/ipykernel_3066/688676489.py:2: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Amazon Sale Report.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN

**index**: An internal DataFrame index, typically a unique identifier for each row.

**order_id:** A unique identifier assigned to each customer order.

**date:** The date when the order was placed.

**status:** The current processing status of the order (e.g., 'Shipped', 'Cancelled', 'Delivered').

**shipped_by:** Indicates whether the item was shipped by 'Amazon' or a 'Merchant'.

**sales_channel_:** The sales platform or channel (e.g., 'Amazon.in').

**delivery_type:** The shipping service level chosen for the delivery (e.g., 'Standard', 'Expedited').

**style:** A specific product style or design code.

**sku:** Stock Keeping Unit, a unique identifier for a product variant (e.g., combining style, size, color).

**category:** The general product category (e.g., 'Set', 'Kurta').

**size:** The size of the product (e.g., 'S', 'M', 'L').

**product_id:** Amazon Standard Identification Number, a unique identifier for products on Amazon.

**delivery_status:** The status of the package from the courier's perspective (e.g., 'Shipped', 'Unshipped').

**quantity:** The number of units of the product ordered.

**currency:** The currency in which the transaction was made (e.g., 'INR').

**price:** The total monetary value of the order.

**ship_city:** The city where the order was shipped.

**ship_state:** The state where the order was shipped
.
**ship_postal_code: **The postal code of the shipping destination.

**ship_country:** The country where the order was shipped.

**promotion_ids:** Identifiers for any promotions or discounts applied to the order.

**b2b:** A boolean indicating if the transaction was Business-to-Business (True/False).
fulfilled_by: How the order was fulfilled (e.g., 'Easy Ship').

**unnamed:_22:** An unnamed column, often indicating residual data or a column that was empty/unimportant in the original data source.

In [ ]:
# Rename columns for better clarity

rename_dict = {
    'fulfilment': 'shipped_by',
    'ship-service-level': 'delivery_type',
    'asin': 'product_id',
    'courier_status': 'delivery_status',
    'qty': 'quantity',
    'amount': 'price'
}

df = df.rename(columns=rename_dict)
df.head(2)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,delivery_type,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN

In [ ]:
print(df.columns)

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'delivery_type', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [ ]:
# Convert all column names to snake_case:snakecaseing

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns = df.columns.str.replace('-','_')
df.head()

,index,order_id,date,status,fulfilment,sales_channel_,delivery_type,style,sku,category,size,asin,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
0,0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             128975 non-null  int64
 1   order_id          128975 non-null  object
 2   date              128975 non-null  object
 3   status            128975 non-null  object
 4   fulfilment        128975 non-null  object
 5   sales_channel_    128975 non-null  object
 6   delivery_type     128975 non-null  object
 7   style             128975 non-null  object
 8   sku               128975 non-null  object
 9   category          128975 non-null  object
 10  size              128975 non-null  object
 11  asin              128975 non-null  object
 12  courier_status    122103 non-null  object
 13  qty               128975 non-null  int64
 14  currency          121180 non-null  object
 15  amount            121180 non-null  float64
 16  ship_city         128942 non-null  object
 17  ship_state        128942 non-null  object
 18  ship_postal_code  128942 non-null  float64
 19  ship_country      128942 non-null  object
 20  promotion_ids     79822 non-null   object
 21  b2b               128975 non-null  bool
 22  fulfilled_by      39277 non-null   object
 23  unnamed:_22       79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [ ]:
df.describe()

               index            qty         amount  ship_postal_code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [ ]:
df.describe(include='all')

,index,order_id,date,status,fulfilment,sales_channel_,delivery_type,style,sku,category,size,asin,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
count,128975.000000,128975,128975,128975,128975,128975,128975,128975,128975,128975,128975,128975,122103,128975.000000,121180,121180.000000,128942,128942,128942.000000,128942,79822,128975,39277,79925
unique,NaN,120378,91,13,2,2,2,1377,7195,9,11,7190,3,NaN,1,NaN,8955,69,NaN,1,5787,2,1,1
top,NaN,403-4984515-8861958,5/3/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-L,Set,M,B09SDXFFQ1,Shipped,NaN,INR,NaN,BENGALURU,MAHARASHTRA,NaN,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Easy Ship,False
freq,NaN,12,2085,77804,89698,128851,88615,4224,773,50284,22711,773,109487,NaN,121180,NaN,11217,22260,NaN,128942,46100,128104,39277,79925
mean,64487.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.904431,NaN,648.561465,NaN,NaN,463966.236509,NaN,NaN,NaN,NaN,NaN
std,37232.019822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.313354,NaN,281.211687,NaN,NaN,191476.764941,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,NaN,110001.000000,NaN,NaN,NaN,NaN,NaN
25%,32243.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,449.000000,NaN,NaN,382421.000000,NaN,NaN,NaN,NaN,NaN
50%,64487.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,605.000000,NaN,NaN,500033.000000,NaN,NaN,NaN,NaN,NaN
75%,96730.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,788.000000,NaN,NaN,600024.000000,NaN,NaN,NaN,NaN,NaN
max,128974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,5584.000000,NaN,NaN,989898.000000,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['ship_country'].unique()
df['fulfilled_by'].unique()

#index: This is redundant as pandas provides its own row index.
#ship_country: If all sales are within 'IN' (India), this is redundant for local analysis.
#Unnamed: 22: This column appears to contain entirely null values.
#curreny: If all sales are within 'IN' (India), INR
#fullfilled by: maximum values are null

df = df.drop(columns=['index', 'ship_country', 'unnamed:_22','currency','fulfilled_by'], axis=1, errors='ignore')
df.head()

,order_id,date,status,fulfilment,sales_channel_,delivery_type,style,sku,category,size,asin,courier_status,qty,amount,ship_city,ship_state,ship_postal_code,promotion_ids,b2b
0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,647.62,MUMBAI,MAHARASHTRA,400081.0,NaN,False
1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,406.00,BENGALURU,KARNATAKA,560085.0,Amazon PLCC Free-Financing Universal Merchant ...,False
2,404-0687676-7273146,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN Core Free Shipping 2015/04/08 23-48-5-108,True
3,403-9615377-8133951,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,NaN,False
4,407-1069790-7240320,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,574.00,CHENNAI,TAMIL NADU,600073.0,NaN,False

In [ ]:
#.copy() ensure my original raw data stays safe and untouched
# Feature Engineering: Creating time-based columns for the dashboard
# Order Month: Extracted from 'Date' to see monthly trends.
# Day of Week: To identify which days (e.g., weekends vs. weekdays) have higher sales.

df_cleaned = df.copy()
df_cleaned['date'] = pd.to_datetime(df_cleaned['date'])
df_cleaned['month'] = df_cleaned['date'].dt.month_name()
df_cleaned['day_of_week'] = df_cleaned['date'].dt.day_name()
df_cleaned.head()

,order_id,date,status,fulfilment,sales_channel_,delivery_type,style,sku,category,size,asin,courier_status,qty,amount,ship_city,ship_state,ship_postal_code,promotion_ids,b2b,month,day_of_week
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,647.62,MUMBAI,MAHARASHTRA,400081.0,NaN,False,April,Saturday
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,406.00,BENGALURU,KARNATAKA,560085.0,Amazon PLCC Free-Financing Universal Merchant ...,False,April,Saturday
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN Core Free Shipping 2015/04/08 23-48-5-108,True,April,Saturday
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,NaN,False,April,Saturday
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,574.00,CHENNAI,TAMIL NADU,600073.0,NaN,False,April,Saturday

In [ ]:
# adding new coloumn using ship_state

df['ship_state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi', nan,
       'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

In [ ]:
# 1. Shipping Region Mapping
state_region_map = {
    'MAHARASHTRA': 'West', 'KARNATAKA': 'South', 'TAMIL NADU': 'South', 'TELANGANA': 'South', 'UTTAR PRADESH': 'North',
    'DELHI': 'North', 'KERALA': 'South', 'WEST BENGAL': 'East', 'ANDHRA PRADESH': 'South', 'GUJARAT': 'West',
    'HARYANA': 'North', 'RAJASTHAN': 'North', 'MADHYA PRADESH': 'Central', 'BIHAR': 'East', 'ODISHA': 'East',
    'PUNJAB': 'North', 'CHATTISGARH': 'Central', 'UTTARAKHAND': 'North', 'JHARKHAND': 'East', 'GOA': 'West',
    'HIMACHAL PRADESH': 'North', 'JAMMU & KASHMIR': 'North', 'ASSAM': 'Northeast', 'MANIPUR': 'Northeast'}

df_cleaned['shipping_region'] = df_cleaned['ship_state'].str.upper().map(state_region_map).fillna('Other')

# 2. Revenue Calculation (Total Amount per SKU)
# We'll create a mapping of SKU to their total sales volume to see business impact

total_sku_revenue = df_cleaned.groupby('sku')['price'].transform('sum')
df_cleaned['sku_revenue'] = total_sku_revenue
df_cleaned.head()

KeyError: 'Column not found: price'

In [ ]:
df_cleaned.isnull().sum()

In [ ]:
# Fill null values with 'No Promotion'

df_cleaned['promotion_ids'].fillna('No Promotion',inplace=True)
df_cleaned.head()

In [ ]:
# Find rows where 'ship_state' is null

null_ship_state = df_cleaned[df_cleaned['ship_state'].isnull()]
null_ship_state.head()

# Find rows where 'Ship-city' is null
null_ship_city = df_cleaned[df_cleaned['ship_city'].isnull()]
null_ship_city.head()

# Find rows where 'ship-postal-code' is null
null_ship_postal_code = df_cleaned[df_cleaned['ship_postal_code'].isnull()]
null_ship_postal_code.head()

# Fill rows
df_cleaned['ship_city'] = df_cleaned['ship_city'].fillna('Unknown')
df_cleaned['ship_state'] = df_cleaned['ship_state'].fillna('Unknown')
df_cleaned['ship_postal_code'] = df_cleaned['ship_postal_code'].fillna(0)
df_cleaned.iloc[1112:1115]

In [ ]:
courier_status_null = df_cleaned[df_cleaned['delivery_status'].isnull()]
courier_status_null.head(2)

In [ ]:
print(courier_status_null['status'].value_counts())

In [ ]:
df_cleaned['delivery_status'].fillna('Cancelled', inplace=True)
print("Null values in 'delivery_status' after filling:")
print(df_cleaned['delivery_status'].isnull().sum())

In [ ]:
amount_null = df_cleaned[df_cleaned['price'].isnull()]
amount_null.head(2)

In [ ]:
df['category'].unique()

In [ ]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile) for 'price' grouped by 'category'
Q1 = df_cleaned.groupby('category')['price'].transform(lambda x: x.quantile(0.25))
Q3 = df_cleaned.groupby('category')['price'].transform(lambda x: x.quantile(0.75))

# Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Define upper and lower bounds for outlier detection
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers: prices outside the calculated bounds for their respective categories
outliers_by_category = df_cleaned[(df_cleaned['price'] < lower_bound) | (df_cleaned['price'] > upper_bound)]

print(f"Number of outliers identified: {len(outliers_by_category)}")
print("Unique categories with outliers:")
print(outliers_by_category['category'].unique())

In [ ]:
# Define the categories to apply median imputation to
target_categories = ['kurta', 'Western Dress', 'Set', 'Blouse', 'Top', 'Bottom', 'Saree']

# Calculate the median price for each category, ignoring NaN values
category_medians = df_cleaned.groupby('category')['price'].median()

# Identify rows that are in target_categories AND have null prices
mask = (df_cleaned['category'].isin(target_categories)) & (df_cleaned['price'].isnull())

# Fill null 'price' values for these specific rows using the pre-calculated category medians
df_cleaned.loc[mask, 'price'] = df_cleaned.loc[mask, 'category'].map(category_medians)

print("Null values in 'price' after median imputation for target categories:")
print(df_cleaned[df_cleaned['category'].isin(target_categories)]['price'].isnull().sum())

In [ ]:
# Define the additional categories to apply mode imputation to
additional_target_categories = ['Ethnic Dress', 'Dupatta']

# Calculate the mode price for each category, handling potential multiple modes by taking the first one
category_modes = df_cleaned.groupby('category')['price'].apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)

# Identify rows that are in additional_target_categories AND have null prices
mask_additional = (df_cleaned['category'].isin(additional_target_categories)) & (df_cleaned['price'].isnull())

# Fill null 'price' values for these specific rows using the pre-calculated category modes
df_cleaned.loc[mask_additional, 'price'] = df_cleaned.loc[mask_additional, 'category'].map(category_modes)

print("Null values in 'price' after mode imputation for additional target categories:")
print(df_cleaned[df_cleaned['category'].isin(additional_target_categories)]['price'].isnull().sum())

In [ ]:
df_cleaned[df_cleaned.duplicated]
df_cleaned.drop_duplicates(inplace=True)

In [ ]:
from google.colab import files

# Convert df_cleaned to CSV
file_name = 'Amazon_Sale_Report_Cleaned.csv'
df_cleaned.to_csv(file_name, index=False)

# Trigger download
files.download(file_name)